"use client";

import { FormEvent, useState } from "react";

import { addComment, deleteComment } from "@/app/social/actions";
import { Button } from "@/components/ui/button";
import { Feedback } from "@/components/ui/feedback";
import { ReportModal } from "@/components/social/report-modal";

type Comment = { id: string; body: string; authorId: string; authorName: string; username: string; createdAt: string };
export function CommentThread({ journalId, journalAuthorId, viewerId, initialComments, initialCount }: { journalId: string; journalAuthorId: string; viewerId: string | null; initialComments: Comment[]; initialCount: number }) {
  const [comments, setComments] = useState(initialComments); const [count, setCount] = useState(initialCount); const [body, setBody] = useState(""); const [pending, setPending] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!viewerId) { setMessage("Masuk untuk menulis komentar."); return; } setPending(true); setMessage(""); const result = await addComment(journalId, journalAuthorId, body); setPending(false); if (result.error) { setMessage(result.error); return; } if (result.comment) { setComments((current) => [...current, result.comment!]); setCount((value) => value + 1); setBody(""); } }
  async function remove(id: string) { const result = await deleteComment(id); if (result.error) { setMessage(result.error); return; } setComments((current) => current.filter((comment) => comment.id !== id)); setCount((value) => Math.max(0, value - 1)); }
  return <section className="card p-5" aria-labelledby="comments-heading"><div className="flex items-end justify-between gap-3"><div><p className="eyebrow">Diskusi</p><h2 id="comments-heading" className="section-title">Komentar</h2></div><span className="text-sm text-muted">{count}</span></div><div className="mt-5 space-y-4">{comments.length ? comments.map((comment) => <article key={comment.id} className="border-b border-[var(--color-border)] pb-4 last:border-0"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{comment.authorName}</p><p className="text-xs text-muted">@{comment.username}</p></div><div className="flex gap-1">{viewerId && (viewerId === comment.authorId || viewerId === journalAuthorId) && <Button variant="ghost" size="sm" onClick={() => remove(comment.id)}>Hapus</Button>}<ReportModal targetType="comment" targetId={comment.id} label="Laporkan" /></div></div><p className="mt-2 text-sm leading-6 text-secondary">{comment.body}</p></article>) : <p className="text-sm leading-6 text-secondary">Belum ada komentar. Mulai percakapannya dengan baik.</p>}</div><form onSubmit={submit} className="mt-5"><label className="field-label" htmlFor="comment-body">Tambahkan komentar</label><textarea id="comment-body" value={body} onChange={(event) => setBody(event.target.value)} maxLength={1000} placeholder={viewerId ? "Tulis komentar…" : "Masuk untuk berkomentar"} disabled={!viewerId || pending} className="field-input min-h-24 resize-y" /><div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-muted">{body.length}/1000</span><Button type="submit" size="sm" disabled={!viewerId || pending || !body.trim()}>{pending ? "Mengirim…" : "Kirim"}</Button></div></form>{message && <Feedback tone="error" title="Komentar belum dapat diproses" description={message} />}</section>;
}
